defmodule SymphonyElixir.Planning do
  @moduledoc """
  CRUD wrapper for orchestrator-owned plans and per-dispatch grades.

  The orchestrator goes through a state machine per issue:

      planning → dispatching → grading → (done | redispatching → dispatching)

  This module is the persistence boundary. The state machine itself lives
  in `SymphonyElixir.Orchestrator` (or a future `Planning.Workflow` module).
  Plan content (rows, file hints, grades) is generated by `Planning.Planner`
  and `Planning.Grader`, which call the LLM.
  """

  import Ecto.Query
  require Logger
  alias SymphonyElixir.Repo
  alias SymphonyElixir.Planning.{Plan, Dispatch}
  alias SymphonyElixir.Tracker

  # ---------------------------------------------------------------------------
  # Plan CRUD
  # ---------------------------------------------------------------------------

  @spec get_plan_by_issue(String.t()) :: Plan.t() | nil
  def get_plan_by_issue(issue_identifier) do
    Repo.one(from(p in Plan, where: p.issue_identifier == ^issue_identifier))
  end

  @spec upsert_plan(map()) :: {:ok, Plan.t()} | {:error, Ecto.Changeset.t()}
  def upsert_plan(%{issue_identifier: issue_identifier} = attrs) do
    case get_plan_by_issue(issue_identifier) do
      nil -> attrs |> Plan.create_changeset() |> Repo.insert()
      plan -> plan |> Plan.update_changeset(attrs) |> Repo.update()
    end
  end

  @spec update_plan(Plan.t(), map()) :: {:ok, Plan.t()} | {:error, Ecto.Changeset.t()}
  def update_plan(%Plan{} = plan, attrs) do
    plan |> Plan.update_changeset(attrs) |> Repo.update()
  end

  @spec set_plan_status(Plan.t(), String.t()) :: {:ok, Plan.t()} | {:error, Ecto.Changeset.t()}
  def set_plan_status(%Plan{} = plan, status), do: update_plan(plan, %{status: status})

  @doc """
  Mirror the plan to the issue's Linear thread as a `## Plan` comment, kept in
  place: posts a new comment the first time (storing `linear_comment_id`) and
  edits that comment afterward. Best-effort — a Linear failure logs and returns
  the plan unchanged so it never blocks planning or grading.
  """
  @spec mirror_plan_to_linear(Plan.t()) :: Plan.t()
  def mirror_plan_to_linear(%Plan{} = plan) do
    body = render_plan_comment(plan)

    case plan.linear_comment_id do
      nil ->
        case Tracker.create_comment_with_id(plan.issue_id, body) do
          {:ok, comment_id} ->
            case update_plan(plan, %{linear_comment_id: comment_id}) do
              {:ok, updated} -> updated
              _ -> plan
            end

          {:error, reason} ->
            Logger.warning("Plan mirror: failed to post comment for #{plan.issue_identifier}: #{inspect(reason)}")
            plan
        end

      comment_id ->
        case Tracker.update_comment(comment_id, body) do
          :ok -> :ok
          {:error, reason} -> Logger.warning("Plan mirror: failed to update comment for #{plan.issue_identifier}: #{inspect(reason)}")
        end

        plan
    end
  rescue
    error ->
      Logger.error("Plan mirror crashed for #{plan.issue_identifier}: #{Exception.message(error)}")
      plan
  end

  @doc "Render the plan as a Linear `## Plan` checklist comment."
  @spec render_plan_comment(Plan.t()) :: String.t()
  def render_plan_comment(%Plan{} = plan) do
    rows = Plan.rows(plan)

    lines =
      Enum.map(rows, fn row ->
        id = row["id"] || "?"
        desc = row["description"] || ""
        mark = state_marker(row["state"])
        state = row["state"] || "missing"
        base = "- #{mark} **#{id}** (#{state}) — #{desc}"

        case row["rationale"] do
          note when is_binary(note) and note != "" -> base <> "\n    - #{note}"
          _ -> base
        end
      end)

    header =
      "## Plan\n\n_Symphony generated this plan and re-grades each row after every dispatch. ✅ done · 🟡 partial · ⬜ missing · ⏭️ deferred._\n"

    body = if lines == [], do: "_(no rows)_", else: Enum.join(lines, "\n")
    header <> "\n" <> body
  end

  defp state_marker("done"), do: "✅"
  defp state_marker("partial"), do: "🟡"
  defp state_marker("deferred"), do: "⏭️"
  defp state_marker(_), do: "⬜"

  @doc """
  Replace the row list inside `plan_json`, preserving any other top-level keys.
  Used when the Grader updates row states after a worker dispatch.
  """
  @spec replace_rows(Plan.t(), [map()]) :: {:ok, Plan.t()} | {:error, Ecto.Changeset.t()}
  def replace_rows(%Plan{plan_json: plan_json} = plan, rows) when is_list(rows) do
    new_plan_json = Map.put(plan_json || %{}, "rows", rows)
    update_plan(plan, %{plan_json: new_plan_json})
  end

  # ---------------------------------------------------------------------------
  # Dispatch CRUD
  # ---------------------------------------------------------------------------

  @spec record_dispatch(map()) :: {:ok, Dispatch.t()} | {:error, Ecto.Changeset.t()}
  def record_dispatch(attrs) do
    attrs |> Dispatch.create_changeset() |> Repo.insert()
  end

  @spec record_grade(Dispatch.t(), map()) :: {:ok, Dispatch.t()} | {:error, Ecto.Changeset.t()}
  def record_grade(%Dispatch{} = dispatch, grade_json) do
    attrs = %{grade_json: grade_json, finished_at: DateTime.utc_now()}
    dispatch |> Dispatch.grade_changeset(attrs) |> Repo.update()
  end

  @spec dispatches_for_plan(Plan.t() | binary()) :: [Dispatch.t()]
  def dispatches_for_plan(%Plan{id: plan_id}), do: dispatches_for_plan(plan_id)

  def dispatches_for_plan(plan_id) when is_binary(plan_id) do
    Dispatch
    |> where([d], d.plan_id == ^plan_id)
    |> order_by([d], asc: d.inserted_at)
    |> Repo.all()
  end
end
