defmodule SymphonyElixir.Planning do
  @moduledoc """
  CRUD wrapper for orchestrator-owned plans and per-dispatch grades.

  The orchestrator goes through a state machine per issue:

      planning → dispatching → grading → (done | redispatching → dispatching)

  This module is the persistence boundary. The state machine itself lives
  in `SymphonyElixir.Orchestrator` (or a future `Planning.Workflow` module).
  Plan content (rows, file hints, grades) is generated by `Planning.Planner`
  and `Planning.Grader`, which call the LLM.
  """

  import Ecto.Query
  alias SymphonyElixir.Repo
  alias SymphonyElixir.Planning.{Plan, Dispatch}

  # ---------------------------------------------------------------------------
  # Plan CRUD
  # ---------------------------------------------------------------------------

  @spec get_plan_by_issue(String.t()) :: Plan.t() | nil
  def get_plan_by_issue(issue_identifier) do
    Repo.one(from(p in Plan, where: p.issue_identifier == ^issue_identifier))
  end

  @spec upsert_plan(map()) :: {:ok, Plan.t()} | {:error, Ecto.Changeset.t()}
  def upsert_plan(%{issue_identifier: issue_identifier} = attrs) do
    case get_plan_by_issue(issue_identifier) do
      nil -> attrs |> Plan.create_changeset() |> Repo.insert()
      plan -> plan |> Plan.update_changeset(attrs) |> Repo.update()
    end
  end

  @spec update_plan(Plan.t(), map()) :: {:ok, Plan.t()} | {:error, Ecto.Changeset.t()}
  def update_plan(%Plan{} = plan, attrs) do
    plan |> Plan.update_changeset(attrs) |> Repo.update()
  end

  @spec set_plan_status(Plan.t(), String.t()) :: {:ok, Plan.t()} | {:error, Ecto.Changeset.t()}
  def set_plan_status(%Plan{} = plan, status), do: update_plan(plan, %{status: status})

  @doc """
  Replace the row list inside `plan_json`, preserving any other top-level keys.
  Used when the Grader updates row states after a worker dispatch.
  """
  @spec replace_rows(Plan.t(), [map()]) :: {:ok, Plan.t()} | {:error, Ecto.Changeset.t()}
  def replace_rows(%Plan{plan_json: plan_json} = plan, rows) when is_list(rows) do
    new_plan_json = Map.put(plan_json || %{}, "rows", rows)
    update_plan(plan, %{plan_json: new_plan_json})
  end

  # ---------------------------------------------------------------------------
  # Dispatch CRUD
  # ---------------------------------------------------------------------------

  @spec record_dispatch(map()) :: {:ok, Dispatch.t()} | {:error, Ecto.Changeset.t()}
  def record_dispatch(attrs) do
    attrs |> Dispatch.create_changeset() |> Repo.insert()
  end

  @spec record_grade(Dispatch.t(), map()) :: {:ok, Dispatch.t()} | {:error, Ecto.Changeset.t()}
  def record_grade(%Dispatch{} = dispatch, grade_json) do
    attrs = %{grade_json: grade_json, finished_at: DateTime.utc_now()}
    dispatch |> Dispatch.grade_changeset(attrs) |> Repo.update()
  end

  @spec dispatches_for_plan(Plan.t() | binary()) :: [Dispatch.t()]
  def dispatches_for_plan(%Plan{id: plan_id}), do: dispatches_for_plan(plan_id)

  def dispatches_for_plan(plan_id) when is_binary(plan_id) do
    Dispatch
    |> where([d], d.plan_id == ^plan_id)
    |> order_by([d], asc: d.inserted_at)
    |> Repo.all()
  end
end
